//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriangleMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triangle
    {
        public int Id { get; set; }
        public string Length_1 { get; set; }
        public string Length_2 { get; set; }
        public string Length_3 { get; set; }
        public bool Equilateral { get; set; }
        public bool Isosceles { get; set; }
        public bool Scalene { get; set; }
        public bool Right_Angle { get; set; }
        public Nullable<System.DateTime> Publish_Time { get; set; }
    }
}
